### ISSUE TITLE
Add method to traverse metric tree, without fetching whole list

### ISSUE THREAD

**Issue by starstuck** [dalmatinerdb/dqe_idx_pg#11]
Some collections may end up having very big metric tree, in tens, even hundreds of thousand metrics. For those collection getting and sending all metrics over a network is very slow.

I think it would be useful to add indexer methods that would allow fetching one level of metrics at a time. We tend to present metrics as a tree in UI anyway, so having api to pull children of single node would be natural extension of that approach.

**Comment by Licenser** [comment]
hmm can you give an example of what you think about I can't quite envision it

**Comment by starstuck** [comment]
Imagine a customer that have very big metric tree. For those customers call to `dqe_idx_pg:metrics/1` takes 1-2 seconds just because of share volume of data. Some of clients will be stateless, so they will not keep whole tree for browsing, instead whenever user clicks a metric part, it will call `metrics/1`, wait those few seconds and show list of available options.

It would be useful to have a function that will give you just short list of available metric completion list

```
dqe_idx_pg:metric_variants(<<"some_collection">>, []) -> [<<"base">>, <<"status">>, <<"nginx">>]
dqe_idx_pg:metric_variants(<<"some_collection">>, [<<"base">>]) -> [<<"cpu">>, <<"memory">>, <<"load">>, <<"disk">>]
```

**Comment by Licenser** [comment]
I like the idea that'd make some sense for discovery, seems also be possible to query sub elements of arrays: https://www.postgresql.org/docs/9.5/static/arrays.html

👍
