### ISSUE TITLE
metrics/1 needs to return the namespace

### ISSUE THREAD

**Issue by Licenser** [dalmatinerdb/dqe_idx_pg#18]
Currently the function only returns metrics, this is problematic as it will be impossible to figure out the namespace of the metrics that way:

https://github.com/dalmatinerdb/dqe_idx_pg/blob/19e8ab91af5c7851b5d78b4464a2b1ac91710787/src/dqe_idx_pg.erl#L70

This also requires changes in the dqe_idx spec.

@szarsti since it was your addition I'll give this to you as you probably need to update your internal code as well

**Comment by starstuck** [comment]
I don't understand the problem. I always perceived metrics independent from name-space. In fact I consider metric being orthogonal dimension to '{name-space, tag, value}' dimension. After all single metric can be used with tags across all name-spaces.

Technically, we could return a list of name-spaces, that are known to be used with that metric, but I can't think of any practical use for such extra information.

**Comment by Licenser** [comment]
I think the problem was too little sleep. You are entirely right, no idea why I thought metrics need namespaces I like mixed it up with dimensions due to a severe lack of coffee at that time. Sorry for the confusion.
