### ISSUE TITLE
sql schema creation fails

### ISSUE THREAD

**Issue by tomashley** [dalmatinerdb/dqe_idx_pg#6]
when running https://github.com/dalmatinerdb/dqe_idx_pg/blob/master/priv/schema.sql

the second 'tags' table fails to create.

is this due to the begin; command halfway down
https://github.com/dalmatinerdb/dqe_idx_pg/blob/master/priv/schema.sql#L19

and there being no commit?

**Comment by Licenser** [comment]
Hi Tom, sorry about that it was a left over from deleting :) slipped me, the begin/commit was wrapped around function creation wich is no longer needed for the default (9.5) schema

**Comment by Licenser** [comment]
removed!
